### ISSUE TITLE
Infinite loop at int.maxvalue

### ISSUE THREAD

**Issue by birdimus** [alexandrnikitin/MPMCQueue.NET#10]
if (cell.Sequence < pos) and if (cell.Sequence < pos +1)
there will be an infinite loop when pos rolls over to int.minvalue, and the queue is either empty or full.

as per the original (1024 cores), enqueue should be:
int dif = cell._sequence- pos;
if(dif == 0)
if(dif < 0)
and dequeue
int dif = cell._sequence - (pos+1);

An example:
cell.Sequence = 2147483633
pos = -2147483648
dif = -15
however cell.Sequence > pos

**Comment by birdimus** [comment]
I know this is marked as obsolete in favor of .net's , however the bounded mpmc queue is still useful to folks looking to avoid runtime allocations, and this is the first result.

**Comment by alexandrnikitin** [comment]
@birdimus thank you for raising the issue! That's interesting finding. Could you please share a repro for it. 
The starting point can be this:
```csharp
var queue = new MPMCQueue(32);
var elem = new object();
for (int i = 0; i < int.MaxValue; i++)
{
    queue.TryEnqueue(elem);
    queue.TryDequeue(out elem);
}
// queue is empty
queue.TryEnqueue(elem); // overflows _enqueuePos
queue.TryDequeue(out elem); // overflows _dequeuePos
```

**Comment by birdimus** [comment]
I've done this:
```
var q = new MPMCQueue(16);

// to avoid waiting for 2 billion queue ops, modify these directly.  This creates an empty queue.  (imagine a queue which has been filled and emptied intmax / size times.
q._enqueuePos = q._dequeuePos = 2147483632;
for(int i=0; i<16; i++){
    q._enqueueBuffer[i].Sequence = 2147483632 + i;
}
        
for(int k = 0; k<8; k++){
    for(int i=0; i<16; i++){
        if(!q.Enqueue(i)){
            // failure
        }
    }
    if(q.Enqueue(17)){
       //failure
    }
    for(int i=0; i<16; i++){
        int v;
        if(q.Dequeue(out v)){
            if(v != i){
                //failure
            }
        }
        else{
             //failure
        }
    }
}
```

**Comment by birdimus** [comment]
Alternatively, if you are willing to wait, this should also cause the issue, once we roll past int.maxvalue.
```
var queue = new MPMCQueue(32);
var elem = new object();
for (uint i = 0; i < uint.MaxValue; i++)
{
    queue.TryEnqueue(elem);
    queue.TryDequeue(out elem);
}
// queue is empty
queue.TryEnqueue(elem); // overflows _enqueuePos
queue.TryDequeue(out elem); // overflows _dequeuePos
```
